### ISSUE TITLE
Bug: When switching categories, on "miscellaneous", the header still stays at "how tags" instead of "miscellaneous tags"

### ISSUE THREAD

**Issue by galaxy-01-6182** [Niloc3/Carl-Bot-Help-Tags#2]
The issue is really really simple, when swithing categories via the ham, on **miscellaneous** category, the header appears to be **How Tags** instead of Miscellaneous tags. It is not a major issue, but still people may confuse the tags with the header ( as the tip appears as well ). I hope this makes sense

By the way, you did a great job niloc, keep moving :)

**Comment by Niloc3** [comment]
Thanks, I’ll fix that now.

**Comment by galaxy-01-6182** [comment]
Great! and good luck
