### ISSUE TITLE
Possible credential leak

### ISSUE THREAD

**Issue by Terra-rian** [Niloc3/Carl-Bot-Help-Tags#3]
In the website's source code (the `index.html`file to be precise), the API key for Google? is just there, where you initialized the firebase app. Not sure if that was intended, but if the key hasn't been properly restricted, it could give anyone control over all of the services assosciated with that key.

Consider using environment variables, or a separate file (probably JSON, that is ignored via a `.gitignore` file) to store sensitive data like that.

**Comment by Niloc3** [comment]
The apiKey just identifies the Firebase project on the Google servers. It is not a security risk for someone to know it. In fact, it is necessary for them to know it, in order for them to interact with the website. Thanks for your concern.
